import { pathwayCatalogSchema } from "./catalog.schema";
import type { Pathway } from "./catalog.types";

const curriculum: Pathway[] = [
  {
    id: "path_networking_foundations",
    slug: "networking-foundations",
    title: "Networking Foundations",
    description: "Build a practical mental model for how modern networks move data.",
    audience: "Complete beginners who want to understand how computer networks work.",
    modules: [
      {
        id: "module_networking_fundamentals",
        slug: "networking-fundamentals",
        title: "Networking Fundamentals",
        description: "Learn the core concepts behind network communication.",
        lessons: [
          {
            id: "lesson_how_networks_communicate",
            slug: "how-networks-communicate",
            title: "How Networks Communicate",
            objective: "Explain how data travels between devices across a network.",
            access: "free",
            published: true,
            estimatedMinutes: 12,
          },
          {
            id: "lesson_hosts_and_network_devices",
            slug: "hosts-and-network-devices",
            title: "Hosts and Network Devices",
            objective: "Identify the devices that create and connect a network.",
            access: "free",
            published: false,
            estimatedMinutes: 12,
          },
          {
            id: "lesson_osi_and_tcp_ip_models",
            slug: "osi-and-tcp-ip-models",
            title: "OSI and TCP/IP Models",
            objective: "Relate common network tasks to the OSI and TCP/IP models.",
            access: "free",
            published: false,
            estimatedMinutes: 15,
          },
          {
            id: "lesson_ipv4_addressing",
            slug: "ipv4-addressing",
            title: "IPv4 Addressing",
            objective: "Read the parts of an IPv4 address and its network role.",
            access: "premium",
            published: false,
            estimatedMinutes: 15,
          },
          {
            id: "lesson_subnetting_fundamentals",
            slug: "subnetting-fundamentals",
            title: "Subnetting Fundamentals",
            objective: "Explain why subnets divide an IPv4 network.",
            access: "premium",
            published: false,
            estimatedMinutes: 18,
          },
          {
            id: "lesson_arp_and_mac_learning",
            slug: "arp-and-mac-learning",
            title: "ARP and MAC Learning",
            objective: "Describe how local networks learn device hardware addresses.",
            access: "premium",
            published: false,
            estimatedMinutes: 14,
          },
          {
            id: "lesson_switching_and_vlan_basics",
            slug: "switching-and-vlan-basics",
            title: "Switching and VLAN Basics",
            objective: "Explain how switches forward traffic and VLANs separate networks.",
            access: "premium",
            published: false,
            estimatedMinutes: 16,
          },
          {
            id: "lesson_routing_and_default_gateways",
            slug: "routing-and-default-gateways",
            title: "Routing and Default Gateways",
            objective: "Explain how routers send traffic beyond a local network.",
            access: "premium",
            published: false,
            estimatedMinutes: 16,
          },
          {
            id: "lesson_tcp_udp_and_ports",
            slug: "tcp-udp-and-ports",
            title: "TCP, UDP, and Ports",
            objective: "Compare transport protocols and explain the purpose of ports.",
            access: "premium",
            published: false,
            estimatedMinutes: 15,
          },
          {
            id: "lesson_dns_dhcp_http_https_and_tls",
            slug: "dns-dhcp-http-https-and-tls",
            title: "DNS, DHCP, HTTP, HTTPS, and TLS",
            objective: "Describe the common services behind everyday network activity.",
            access: "premium",
            published: false,
            estimatedMinutes: 20,
          },
          {
            id: "lesson_nat_and_basic_firewall_concepts",
            slug: "nat-and-basic-firewall-concepts",
            title: "NAT and Basic Firewall Concepts",
            objective: "Explain how NAT and firewalls control network connections.",
            access: "premium",
            published: false,
            estimatedMinutes: 15,
          },
          {
            id: "lesson_end_to_end_packet_journey",
            slug: "end-to-end-packet-journey",
            title: "End-to-End Packet Journey",
            objective: "Trace a packet from an application to its destination.",
            access: "premium",
            published: false,
            estimatedMinutes: 20,
          },
        ],
      },
    ],
  },
];

export const pathways = pathwayCatalogSchema.parse(curriculum);
