import { pathwayCatalogSchema } from "./catalog.schema";
import type { LessonSummary, Pathway } from "./catalog.types";

type PlannedLesson = Omit<LessonSummary, "published" | "sections">;

function plannedLesson(lesson: PlannedLesson): LessonSummary {
  return { ...lesson, published: false };
}

const stablePublishedSlugs = {
  whatIsANetwork: "how-networks-communicate",
  hostsAndInterfaces: "hosts-and-network-devices",
  osiAndTcpIp: "osi-and-tcp-ip-models",
} as const;

const curriculum: Pathway[] = [
  {
    id: "path_networking_foundations",
    slug: "networking-foundations",
    title: "Networking Foundations",
    description: "Build a practical mental model for how modern networks move data.",
    audience: "Complete beginners who want to understand how computer networks work.",
    modules: [
      {
        id: "module_network_and_device_essentials",
        slug: "network-and-device-essentials",
        title: "Network and Device Essentials",
        description: "Learn the physical connections, devices, and models behind communication.",
        lessons: [
          {
            id: "lesson_how_networks_communicate", slug: stablePublishedSlugs.whatIsANetwork,
            title: "What Is a Computer Network?",
            objective: "Explain why networks exist and identify the ingredients required for communication.",
            seo: { title: "How Networks Communicate: A Beginner's Guide", description: "Learn the decisions that move data between hosts and trace a packet across a network." },
            published: true, estimatedMinutes: 12,
            sections: [
              { id: "communication-decisions", label: "Communication decisions", access: "public" },
              { id: "packet-journey", label: "Interactive packet journey", access: "public" },
              { id: "wireshark-check", label: "Basic Wireshark check", access: "account" },
              { id: "knowledge-check", label: "Knowledge check", access: "account" },
              { id: "interview-scenario", label: "Interview scenario", access: "account" },
              { id: "pro-deep-dive", label: "Pro Deep Dive", access: "pro", preview: "Check the governing RFC and relevant read-only vendor diagnostics." },
            ],
          },
          {
            id: "lesson_hosts_and_network_devices", slug: stablePublishedSlugs.hostsAndInterfaces,
            title: "Hosts, Clients, Servers and Network Interfaces",
            objective: "Identify end hosts and interfaces and explain client and server roles.",
            seo: { title: "Hosts and Network Devices: Learn the Basics", description: "Identify hosts and network devices, then predict each packet's path through a topology." },
            published: true, estimatedMinutes: 20,
            sections: [
              { id: "what-is-a-host", label: "What is a host?", access: "public" },
              { id: "connecting-devices", label: "Devices that connect hosts", access: "public" },
              { id: "explore-topology", label: "Explore the topology", access: "public" },
              { id: "compare-journeys", label: "Compare packet journeys", access: "public" },
              { id: "windows-checks", label: "Windows checks", access: "account" },
              { id: "wireshark-checks", label: "Wireshark checks", access: "account" },
              { id: "test-understanding", label: "Test your understanding", access: "account" },
              { id: "summary", label: "Summary", access: "account" },
              { id: "pro-deep-dive", label: "Pro Deep Dive", access: "pro", preview: "Check the governing RFC and relevant read-only vendor diagnostics." },
            ],
          },
          {
            id: "lesson_cables_fibre_wireless_and_network_connections", slug: "cables-fibre-wireless-and-network-connections", title: "Cables, Fibre, Wireless and Network Connections",
            objective: "Choose an appropriate connection medium and explain duplex, speed, signal, and link state at a beginner level.",
            seo: { title: "Network Cables, Fibre and Wireless Basics", description: "Compare copper, fibre, and wireless links to choose suitable connections and recognize beginner-friendly link symptoms." },
            published: true,
            estimatedMinutes: 20,
            sections: [
              { id: "how-connections-carry-data", label: "How connections carry data", access: "public" },
              { id: "connection-qualities", label: "Connection qualities", access: "public" },
              { id: "copper-ethernet", label: "Copper Ethernet", access: "public" },
              { id: "fibre-connections", label: "Fibre connections", access: "public" },
              { id: "wireless-connections", label: "Wireless connections", access: "public" },
              { id: "compare-media", label: "Compare connection media", access: "public" },
              { id: "design-a-connection", label: "Design a connection", access: "account" },
              { id: "diagnose-link-symptoms", label: "Diagnose link symptoms", access: "account" },
              { id: "knowledge-check-summary", label: "Knowledge check and summary", access: "account" },
              { id: "pro-deep-dive", label: "Pro Deep Dive", access: "pro", preview: "Explore optical budgets, wireless channel analysis, advanced troubleshooting, standards checks, and interview preparation." },
            ],
          },
          {
            id: "lesson_hubs_bridges_and_switches", slug: "hubs-bridges-and-switches", title: "Hubs, Bridges and Switches",
            objective: "Explain why hubs repeat signals while bridges and switches make link-layer forwarding decisions.",
            seo: { title: "Hubs, Bridges and Switches Explained", description: "See how hubs repeat traffic while bridges and switches make selective link-layer forwarding choices on a local network." },
            published: true, estimatedMinutes: 20,
            sections: [
              { id: "one-local-ethernet-conversation", label: "One local Ethernet conversation", access: "public" },
              { id: "what-a-hub-does", label: "What a hub does", access: "public" },
              { id: "why-bridges-changed-ethernet", label: "Why bridges changed Ethernet", access: "public" },
              { id: "how-a-switch-learns", label: "How a switch learns", access: "public" },
              { id: "how-a-switch-forwards", label: "How a switch forwards", access: "public" },
              { id: "compare-hub-bridge-switch", label: "Compare hub, bridge and switch", access: "public" },
              { id: "forward-the-frame", label: "Forward the frame", access: "account" },
              { id: "diagnose-local-switching-symptoms", label: "Diagnose local switching symptoms", access: "account" },
              { id: "knowledge-check-summary", label: "Knowledge check and summary", access: "account" },
              { id: "pro-deep-dive", label: "Pro Deep Dive", access: "pro", preview: "Discover future advanced switching practice and career preparation." },
            ],
          },
          {
            id: "lesson_unicast_broadcast_and_multicast_communication",
            slug: "unicast-broadcast-and-multicast-communication",
            title: "Unicast, Broadcast and Multicast Communication",
            objective: "Identify a transmission's delivery scope and predict which interfaces receive, accept, or forward it.",
            seo: {
              title: "Unicast, Broadcast and Multicast Explained",
              description: "Compare unicast, broadcast, and multicast traffic and predict how switches, hosts, and routers handle each delivery type.",
            },
            published: true,
            estimatedMinutes: 22,
            sections: [
              { id: "why-delivery-scope-matters", label: "Why delivery scope matters", access: "public" },
              { id: "unicast-one-destination", label: "Unicast: one intended destination", access: "public" },
              { id: "broadcast-local-domain", label: "Broadcast: the local broadcast domain", access: "public" },
              { id: "multicast-receiver-group", label: "Multicast: an interested receiver group", access: "public" },
              { id: "unknown-unicast-is-not-broadcast", label: "Unknown unicast is not broadcast", access: "public" },
              { id: "compare-delivery-types", label: "Compare delivery types", access: "public" },
              { id: "delivery-scope-player", label: "Interactive delivery-scope player", access: "public" },
              { id: "predict-delivery", label: "Predict traffic delivery", access: "account" },
              { id: "diagnose-delivery-scope", label: "Diagnose delivery-scope scenarios", access: "account" },
              { id: "packet-evidence", label: "Packet evidence", access: "account" },
              { id: "knowledge-check-summary", label: "Knowledge check and summary", access: "account" },
              { id: "pro-deep-dive", label: "Pro Deep Dive", access: "pro", preview: "Discover future multicast operations, advanced packet analysis, and production troubleshooting." },
            ],
          },
          {
            id: "lesson_routers_default_gateways_and_network_boundaries", slug: "routers-default-gateways-and-network-boundaries", title: "Routers, Default Gateways and Network Boundaries",
            objective: "Decide whether a destination is local or remote and identify the first next hop.",
            seo: { title: "Routers and Default Gateways Basics", description: "Learn how a host decides between local delivery and a default gateway when it needs to reach a remote destination." },
            published: true, estimatedMinutes: 20,
            sections: [
              { id: "why-network-boundaries-matter", label: "Why network boundaries matter", access: "public" },
              { id: "what-a-router-does", label: "What a router does", access: "public" },
              { id: "local-or-remote", label: "Local or remote?", access: "public" },
              { id: "default-gateway", label: "The default gateway", access: "public" },
              { id: "direct-and-routed-delivery", label: "Direct delivery and routed delivery", access: "public" },
              { id: "what-changes-at-each-hop", label: "What changes at each hop", access: "public" },
              { id: "route-decision-player", label: "Interactive route-decision player", access: "public" },
              { id: "read-a-basic-routing-table", label: "Read a basic routing table", access: "account" },
              { id: "diagnose-gateway-boundary-problems", label: "Diagnose gateway and boundary problems", access: "account" },
              { id: "knowledge-check-summary", label: "Knowledge check and summary", access: "account" },
              { id: "pro-deep-dive", label: "Pro Deep Dive", access: "pro", preview: "Explore advanced route selection, packet analysis, standards checks, production troubleshooting, and interview preparation." },
            ],
          },
          {
            id: "lesson_access_points_modems_onts_and_firewalls", slug: "access-points-modems-onts-and-firewalls", title: "Access Points, Modems, ONTs and Firewalls",
            objective: "Explain where common edge devices fit and distinguish access, conversion, routing, and security roles.",
            seo: { title: "Access Points, Modems, ONTs and Firewalls", description: "Place common home and office edge devices in a topology and distinguish their access, conversion, routing, and boundary roles." }, estimatedMinutes: 20,
            published: true,
            sections: [
              { id: "one-box-many-jobs", label: "One box, many jobs", access: "public" },
              { id: "access-points-bridge-wireless", label: "Access points bridge wireless", access: "public" },
              { id: "modems-and-onts-convert-signals", label: "Modems and ONTs convert signals", access: "public" },
              { id: "routers-and-firewalls-set-boundaries", label: "Routers and firewalls set boundaries", access: "public" },
              { id: "compare-edge-devices", label: "Compare edge devices", access: "public" },
              { id: "interactive-edge-journey", label: "Interactive edge-device journey", access: "public" },
              { id: "identify-device-roles", label: "Identify device roles", access: "account" },
              { id: "diagnose-edge-failures", label: "Diagnose edge failures", access: "account" },
              { id: "knowledge-check-summary", label: "Knowledge check and summary", access: "account" },
              { id: "pro-deep-dive", label: "Pro Deep Dive", access: "pro", preview: "Explore firewall state and policy, advanced packet evidence, standards checks, NAT, VPNs, and vendor diagnostics." },
            ],
          },
          {
            id: "lesson_osi_and_tcp_ip_models", slug: stablePublishedSlugs.osiAndTcpIp, title: "OSI and TCP/IP Models",
            objective: "Relate common network tasks to the OSI and TCP/IP models.",
            seo: { title: "OSI and TCP/IP Models Explained", description: "Connect the OSI and TCP/IP models to practical network tasks, packet layers, and troubleshooting." },
            published: true, estimatedMinutes: 18,
            sections: [
              { id: "why-layers", label: "Why layered models exist", access: "account" },
              { id: "osi-model", label: "The seven OSI layers", access: "account" },
              { id: "tcp-ip-model", label: "The four-layer TCP/IP model", access: "account" },
              { id: "model-mapping", label: "OSI-to-TCP/IP mapping", access: "account" },
              { id: "encapsulation-lab", label: "Interactive encapsulation and decapsulation", access: "account" },
              { id: "device-layer-scope", label: "What each network device examines", access: "account" },
              { id: "wireshark-layers", label: "Wireshark layer identification", access: "account" },
              { id: "troubleshooting-interview", label: "Troubleshooting and interview scenarios", access: "account" },
              { id: "knowledge-summary", label: "Knowledge check and summary", access: "account" },
              { id: "pro-deep-dive", label: "Pro Deep Dive", access: "pro", preview: "Check the governing RFC and relevant read-only vendor diagnostics." },
            ],
          },
          {
            id: "lesson_first_packet_journey_through_a_small_network", slug: "first-packet-journey-through-a-small-network", title: "A Packet’s First Journey Through a Small Network",
            objective: "Narrate an end-to-end exchange using the concepts from Lessons 1–8.",
            seo: { title: "A Packet's First Journey Through a Network", description: "Follow a first end-to-end packet exchange and connect host, link, switch, router, frame, and response decisions." }, estimatedMinutes: 25,
            published: true,
            sections: [
              { id: "before-the-first-frame", label: "Before the first frame", access: "public" },
              { id: "resolve-the-next-hop", label: "Resolve the next hop", access: "public" },
              { id: "switch-and-route-the-request", label: "Switch and route the request", access: "public" },
              { id: "return-traffic", label: "Return traffic", access: "public" },
              { id: "complete-packet-journey", label: "Complete packet journey", access: "public" },
              { id: "match-evidence-to-the-journey", label: "Match evidence to the journey", access: "account" },
              { id: "troubleshoot-the-first-failed-hop", label: "Troubleshoot the first failed hop", access: "account" },
              { id: "knowledge-check-summary", label: "Knowledge check and summary", access: "account" },
              { id: "pro-deep-dive", label: "Pro Deep Dive", access: "pro", preview: "Explore capture-position blind spots, advanced Wireshark checks, standards evidence, and interview scenarios." },
            ],
          },
        ],
      },
      {
        id: "module_ethernet_switching_and_local_networks", slug: "ethernet-switching-and-local-networks", title: "Ethernet, Switching and Local Networks",
        description: "Understand frames, local delivery, switching decisions, and broadcast boundaries.",
        lessons: [
          {
            id: "lesson_ethernet_frames_and_mac_addresses", slug: "ethernet-frames-and-mac-addresses", title: "Ethernet Frames and MAC Addresses",
            objective: "Read the purpose of core Ethernet fields and distinguish unicast, broadcast, and multicast destinations.",
            seo: { title: "Ethernet Frames and MAC Addresses", description: "Inspect Ethernet frame fields and learn how unicast, broadcast, and multicast MAC destinations guide local delivery." }, estimatedMinutes: 24,
            published: true,
            sections: [
              { id: "ethernet-delivers-on-the-local-link", label: "Ethernet delivers on the local link", access: "public" },
              { id: "read-an-ethernet-frame", label: "Read an Ethernet frame", access: "public" },
              { id: "understand-mac-addresses", label: "Understand MAC addresses", access: "public" },
              { id: "delivery-addresses", label: "Unicast, broadcast, multicast and unknown unicast", access: "public" },
              { id: "interactive-frame-delivery", label: "Interactive frame delivery", access: "public" },
              { id: "inspect-frame-evidence", label: "Inspect frame evidence", access: "account" },
              { id: "diagnose-frame-problems", label: "Diagnose frame problems", access: "account" },
              { id: "knowledge-check-summary", label: "Knowledge check and summary", access: "account" },
              { id: "pro-deep-dive", label: "Pro Deep Dive", access: "pro", preview: "Explore standards validation, unusual frames, capture limitations, and difficult interview scenarios." },
            ],
          },
          {
            id: "lesson_how_switches_learn_and_forward", slug: "how-switches-learn-and-forward", title: "How Switches Learn and Forward",
            objective: "Build and use a MAC address table to predict forwarding, filtering, and flooding.",
            seo: { title: "How Network Switches Learn and Forward", description: "Build a switch MAC table step by step to predict known forwarding, filtering, unknown flooding, and host movement." }, estimatedMinutes: 24,
            published: true,
            sections: [
              { id: "the-switch-decision-cycle", label: "The switch decision cycle", access: "public" },
              { id: "learn-the-source-address", label: "Learn the source address", access: "public" },
              { id: "look-up-the-destination", label: "Look up the destination", access: "public" },
              { id: "forward-filter-or-flood", label: "Forward, filter or flood", access: "public" },
              { id: "interactive-switch-learning", label: "Interactive switch learning", access: "public" },
              { id: "read-mac-table-evidence", label: "Read MAC-table evidence", access: "account" },
              { id: "diagnose-switching-behaviour", label: "Diagnose switching behaviour", access: "account" },
              { id: "knowledge-check-summary", label: "Knowledge check and summary", access: "account" },
              { id: "pro-deep-dive", label: "Pro Deep Dive", access: "pro", preview: "Explore VLAN-aware tables, managed-switch evidence, packet captures, standards checks, and advanced interview scenarios." },
            ],
          },
          {
            id: "lesson_arp_and_local_delivery", slug: "arp-and-local-delivery", title: "ARP and Local Delivery",
            objective: "Explain how IPv4 nodes resolve a local next-hop IP address to a MAC address.",
            seo: { title: "ARP and Local Network Delivery", description: "Learn how an IPv4 host uses ARP to resolve a local destination or gateway IP address into a usable MAC address." }, estimatedMinutes: 24,
            published: true,
            sections: [
              { id: "why-arp-exists", label: "Why ARP exists", access: "public" },
              { id: "choose-the-next-hop-first", label: "Choose the next hop first", access: "public" },
              { id: "request-reply-and-cache", label: "Request, reply and cache", access: "public" },
              { id: "interactive-arp-journey", label: "Interactive ARP journey", access: "public" },
              { id: "arp-variants-and-boundaries", label: "ARP variants and boundaries", access: "public" },
              { id: "inspect-neighbour-evidence", label: "Inspect neighbour evidence", access: "account" },
              { id: "troubleshoot-arp-methodically", label: "Troubleshoot ARP methodically", access: "account" },
              { id: "knowledge-check-summary", label: "Knowledge check and summary", access: "account" },
              { id: "pro-deep-dive", label: "Pro Deep Dive", access: "pro", preview: "Explore RFC-guided cache behavior, ARP security evidence, advanced captures, production troubleshooting, and interview preparation." },
            ],
          },
          {
            id: "lesson_vlans_access_ports_and_trunks", slug: "vlans-access-ports-and-trunks", title: "VLANs, Access Ports and Trunks",
            objective: "Explain why VLANs create separate broadcast domains and how access and trunk links carry them.",
            seo: { title: "VLANs, Access Ports and Trunks", description: "Discover how VLANs separate broadcast domains and how access and trunk links carry traffic between network devices." }, estimatedMinutes: 24,
            published: true,
            sections: [
              { id: "why-vlans-exist", label: "Why VLANs exist", access: "public" },
              { id: "access-ports-and-membership", label: "Access ports and membership", access: "public" },
              { id: "interactive-vlan-membership", label: "Interactive VLAN membership", access: "public" },
              { id: "trunks-and-802-1q", label: "Trunks and 802.1Q", access: "public" },
              { id: "interactive-tag-journey", label: "Interactive tag journey", access: "public" },
              { id: "allowed-vlans-and-routing-boundary", label: "Allowed VLANs and routing boundary", access: "public" },
              { id: "read-port-and-capture-evidence", label: "Read port and capture evidence", access: "account" },
              { id: "solve-vlan-reachability", label: "Solve VLAN reachability", access: "account" },
              { id: "knowledge-check-summary", label: "Knowledge check and summary", access: "account" },
              { id: "pro-deep-dive", label: "Pro Deep Dive", access: "pro", preview: "Diagnose native and allowed VLAN mismatches, trace advanced inter-VLAN paths, inspect standards-guided captures, and prepare for production and interview scenarios." },
            ],
          },
        ],
      },
      {
        id: "module_ip_addressing_and_routing", slug: "ip-addressing-and-routing", title: "IP Addressing and Routing",
        description: "Learn addressing, subnetting, routing choices, and network control evidence.",
        lessons: [
          {
            id: "lesson_ipv4_addressing", slug: "ipv4-addressing", title: "IPv4 Addressing",
            objective: "Read dotted-decimal addresses and prefixes and distinguish network, host, private, public, loopback, link-local, and documentation ranges.",
            seo: { title: "IPv4 Addressing for Beginners", description: "Read IPv4 addresses and prefixes, then identify network, host, private, public, loopback, link-local, and documentation ranges." }, estimatedMinutes: 25,
            published: true,
            sections: [
              { id: "read-an-ipv4-address", label: "Read an IPv4 address", access: "public" },
              { id: "dotted-decimal-and-binary", label: "Dotted decimal and binary", access: "public" },
              { id: "interactive-binary-explorer", label: "Interactive binary explorer", access: "public" },
              { id: "prefixes-network-and-host", label: "Prefixes, network and host portions", access: "public" },
              { id: "interactive-address-boundary", label: "Interactive address boundary", access: "public" },
              { id: "special-address-ranges", label: "Special address ranges", access: "public" },
              { id: "inspect-address-evidence", label: "Inspect address evidence", access: "account" },
              { id: "troubleshoot-addressing", label: "Troubleshoot addressing", access: "account" },
              { id: "knowledge-check-summary", label: "Knowledge check and summary", access: "account" },
              { id: "pro-deep-dive", label: "Pro Deep Dive", access: "pro", preview: "Explore special-use ranges, overlapping plans, capture evidence, production diagnostics, and interview scenarios." },
            ],
          },
          {
            id: "lesson_subnetting_fundamentals", slug: "subnetting-fundamentals", title: "Subnetting Fundamentals",
            objective: "Calculate network boundaries, usable ranges, broadcast addresses, and host capacity for common IPv4 prefixes.",
            seo: { title: "Subnetting Fundamentals for IPv4", description: "Calculate common IPv4 subnet boundaries, usable ranges, broadcast addresses, and host capacity with understandable methods." }, estimatedMinutes: 25,
            published: true,
            sections: [
              { id: "why-subnetting-exists", label: "Why subnetting exists", access: "public" },
              { id: "prefix-length-and-mask", label: "Prefix length and subnet mask", access: "public" },
              { id: "network-and-host-portions", label: "Network and host portions", access: "public" },
              { id: "interactive-subnet-boundary", label: "Interactive subnet boundary", access: "public" },
              { id: "repeatable-calculation-method", label: "A repeatable calculation method", access: "public" },
              { id: "ranges-and-capacity", label: "Ranges and capacity", access: "public" },
              { id: "interactive-subnet-scenarios", label: "Interactive subnet scenarios", access: "public" },
              { id: "special-prefixes", label: "Special prefixes", access: "public" },
              { id: "local-or-gateway", label: "Local delivery or the default gateway", access: "public" },
              { id: "inspect-subnet-evidence", label: "Inspect subnet evidence", access: "account" },
              { id: "practice-subnet-planning", label: "Practice subnet planning", access: "account" },
              { id: "troubleshoot-subnetting", label: "Troubleshoot subnetting", access: "account" },
              { id: "knowledge-check-summary", label: "Knowledge check and summary", access: "account" },
              { id: "pro-deep-dive", label: "Pro Deep Dive", access: "pro", preview: "Plan with VLSM, validate summarization, solve awkward prefixes, and diagnose production overlap." },
            ],
          },
          {
            id: "lesson_ipv6_fundamentals", slug: "ipv6-fundamentals", title: "IPv6 Fundamentals",
            objective: "Read and shorten IPv6 addresses and explain prefixes, link-local/global addresses, multicast, Neighbor Discovery, SLAAC, and default-router discovery.",
            seo: { title: "IPv6 Fundamentals for Beginners", description: "Read and shorten IPv6 addresses while learning prefixes, link-local and global addresses, multicast, SLAAC, and Neighbor Discovery." }, estimatedMinutes: 25,
            published: true,
            sections: [
              { id: "why-ipv6-exists", label: "Why IPv6 exists", access: "public" },
              { id: "address-structure-hex", label: "Address structure and hexadecimal", access: "public" },
              { id: "expand-shorten", label: "Expand and shorten addresses", access: "public" },
              { id: "interactive-address-explorer", label: "Interactive address explorer", access: "public" },
              { id: "prefixes-interface-identifiers", label: "Prefixes and interface identifiers", access: "public" },
              { id: "address-types-scopes", label: "Address types and scopes", access: "public" },
              { id: "no-broadcast", label: "IPv6 has no broadcast", access: "public" },
              { id: "neighbor-discovery-icmpv6", label: "Neighbor Discovery and ICMPv6", access: "public" },
              { id: "interactive-ndp-slaac", label: "Interactive NDP and SLAAC", access: "public" },
              { id: "default-router-local-delivery", label: "Local delivery or default router", access: "public" },
              { id: "inspect-ipv6-evidence", label: "Inspect IPv6 evidence", access: "account" },
              { id: "practice-ipv6", label: "Practise IPv6 interpretation", access: "account" },
              { id: "troubleshoot-ipv6", label: "Troubleshoot IPv6", access: "account" },
              { id: "knowledge-check-summary", label: "Knowledge check and summary", access: "account" },
              { id: "pro-deep-dive", label: "Pro Deep Dive", access: "pro", preview: "Diagnose Router Advertisements, DAD, interface identifiers, dual-stack selection, and production ICMPv6." },
            ],
          },
          {
            id: "lesson_routing_tables_and_default_routes", slug: "routing-tables-and-default-routes", title: "Routing, Routing Tables and Default Routes",
            objective: "Read a basic routing table and choose a route using longest-prefix match and administrative/metric concepts at the appropriate depth.",
            seo: { title: "Routing Tables and Default Routes", description: "Read a basic routing table and use longest-prefix matching with metrics to choose an interface and next hop." }, estimatedMinutes: 25,
            published: true,
            sections: [
              { id: "why-routing-exists", label: "Why routing exists", access: "public" },
              { id: "route-table-anatomy", label: "Route-table anatomy", access: "public" },
              { id: "route-sources", label: "Connected, static, learned, and default routes", access: "public" },
              { id: "how-prefix-matching-works", label: "How prefix matching works", access: "public" },
              { id: "interactive-route-selection", label: "Interactive route selection", access: "public" },
              { id: "longest-prefix-match", label: "Longest-prefix match", access: "public" },
              { id: "administrative-distance", label: "Administrative distance", access: "public" },
              { id: "route-metric", label: "Route metric", access: "public" },
              { id: "next-hop-outgoing-interface", label: "Next hop and outgoing interface", access: "public" },
              { id: "interactive-hop-by-hop-forwarding", label: "Interactive hop-by-hop forwarding", access: "public" },
              { id: "ipv4-ipv6-routing", label: "IPv4 and IPv6 routing", access: "public" },
              { id: "no-route-packet-disposal", label: "No route and packet disposal", access: "public" },
              { id: "inspect-routing-evidence", label: "Inspect routing evidence", access: "account" },
              { id: "guided-routing-practice", label: "Guided routing practice", access: "account" },
              { id: "troubleshoot-routing", label: "Troubleshoot routing", access: "account" },
              { id: "knowledge-check-summary", label: "Knowledge check and summary", access: "account" },
              { id: "pro-deep-dive", label: "Pro Deep Dive", access: "pro", preview: "Trace recursive lookups, ECMP, dynamic best paths, policy routing, VRFs, convergence, and production failures." },
            ],
          },
          {
            id: "lesson_icmp_ping_and_path_discovery", slug: "icmp-ping-and-path-discovery", title: "ICMP, Ping and Path Discovery",
            objective: "Use ICMP as control/error evidence and explain what ping and traceroute do and do not prove.",
            seo: { title: "ICMP, Ping and Path Discovery", description: "Use ICMP evidence to understand what ping and traceroute reveal about reachability, failures, and network paths." }, estimatedMinutes: 20,
            published: true,
            sections: [
              { id: "why-icmp-exists", label: "Why ICMP exists", access: "public" },
              { id: "icmp-message-anatomy", label: "ICMP message anatomy", access: "public" },
              { id: "informational-and-error-messages", label: "Informational and error messages", access: "public" },
              { id: "echo-request-and-reply", label: "Echo request and echo reply", access: "public" },
              { id: "interactive-ping-evidence", label: "Interactive ping and ICMP evidence", access: "public" },
              { id: "what-successful-ping-proves", label: "What successful ping proves", access: "public" },
              { id: "timeouts-loss-and-rtt", label: "Timeouts, loss, and round-trip time", access: "public" },
              { id: "destination-unreachable", label: "Destination Unreachable", access: "public" },
              { id: "ttl-exceeded", label: "TTL Exceeded", access: "public" },
              { id: "interactive-traceroute-discovery", label: "Interactive traceroute path discovery", access: "public" },
              { id: "why-traceroute-can-be-incomplete", label: "Why traceroute can be incomplete", access: "public" },
              { id: "safe-conclusions", label: "Safe conclusions", access: "public" },
              { id: "inspect-icmp-evidence", label: "Inspect ICMP evidence", access: "account" },
              { id: "guided-icmp-diagnosis", label: "Guided ICMP diagnosis", access: "account" },
              { id: "troubleshoot-icmp", label: "Troubleshoot ICMP", access: "account" },
              { id: "knowledge-check-summary", label: "Knowledge check and summary", access: "account" },
              { id: "pro-deep-dive", label: "Pro Deep Dive", access: "pro", preview: "Diagnose filtered or rate-limited ICMP, IPv4 Path MTU Discovery, asymmetric paths, protocol-specific probes, and deeper captures." },
            ],
          },
        ],
      },
      {
        id: "module_transport_and_application_services", slug: "transport-and-application-services", title: "Transport and Application Services",
        description: "Explore transport behavior and the services applications rely on.",
        lessons: [
          plannedLesson({
            id: "lesson_tcp_udp_and_ports", slug: "tcp-udp-and-ports", title: "TCP, UDP and Ports",
            objective: "Compare TCP and UDP, explain sockets/ports, and trace connection establishment, reliability, flow, and closure at a foundational level.",
            seo: { title: "TCP, UDP and Network Ports", description: "Compare TCP and UDP, learn how sockets and ports identify conversations, and trace foundational connection behavior." }, estimatedMinutes: 25,
          }),
          plannedLesson({
            id: "lesson_dhcp_and_automatic_address_configuration", slug: "dhcp-and-automatic-address-configuration", title: "DHCP and Automatic Address Configuration",
            objective: "Trace address acquisition and identify the supplied address, prefix, gateway, DNS, and lease information.",
            seo: { title: "DHCP and Automatic Address Configuration", description: "Trace DHCP address configuration and identify the address, prefix, gateway, DNS servers, and lease details it supplies." }, estimatedMinutes: 20,
          }),
          plannedLesson({
            id: "lesson_dns_and_name_resolution", slug: "dns-and-name-resolution", title: "DNS and Name Resolution",
            objective: "Trace recursive name resolution and distinguish stub resolver, recursive resolver, authoritative server, common records, caching, and response codes.",
            seo: { title: "DNS and Name Resolution Explained", description: "Follow a DNS query through stub, recursive, and authoritative resolvers while learning records, caching, and response codes." }, estimatedMinutes: 25,
          }),
          plannedLesson({
            id: "lesson_http_https_tls_and_essential_network_services", slug: "http-https-tls-and-essential-network-services", title: "HTTP, HTTPS, TLS and Essential Network Services",
            objective: "Relate application requests to DNS, transport, TLS, and HTTP and recognize the purposes of SSH, NTP, and common service ports without memorizing an excessive list.",
            seo: { title: "HTTP, HTTPS, TLS and Network Services", description: "Trace a browser request through DNS, transport, TLS, and HTTP while recognizing the roles of SSH, NTP, and service ports." }, estimatedMinutes: 25,
          }),
        ],
      },
      {
        id: "module_nat_and_internet_communication", slug: "nat-and-internet-communication", title: "NAT and Internet Communication",
        description: "Trace address translation through an end-to-end internet exchange.",
        lessons: [
          plannedLesson({
            id: "lesson_nat_pat_and_the_complete_internet_packet_journey", slug: "nat-pat-and-the-complete-internet-packet-journey", title: "NAT, PAT and the Complete Internet Packet Journey",
            objective: "Explain address/port translation and trace a browser exchange from a private host to an internet service and back.",
            seo: { title: "NAT, PAT and the Internet Packet Journey", description: "Trace a browser exchange from a private host to an internet service and see how NAT and PAT translate addresses and ports." }, estimatedMinutes: 25,
          }),
        ],
      },
      {
        id: "module_packet_analysis_and_troubleshooting", slug: "packet-analysis-and-troubleshooting", title: "Packet Analysis and Troubleshooting",
        description: "Apply evidence-driven, layer-aware troubleshooting to network faults.",
        lessons: [
          plannedLesson({
            id: "lesson_systematic_network_troubleshooting_capstone", slug: "systematic-network-troubleshooting-capstone", title: "Systematic Network Troubleshooting Capstone",
            objective: "Apply a repeatable, layer-aware troubleshooting method and communicate evidence, scope, hypothesis, test, result, and next action.",
            seo: { title: "Systematic Network Troubleshooting", description: "Practice a repeatable layer-aware troubleshooting method that documents evidence, scope, hypotheses, tests, results, and next actions." }, estimatedMinutes: 25,
          }),
        ],
      },
    ],
  },
];

export const pathways = pathwayCatalogSchema.parse(curriculum);
