import { parsePacketFlowScenario, type PacketFlowScenario } from "@/features/packet-flow/packet-flow.schema";

export const bgpSessionEstablishmentScenario: PacketFlowScenario = parsePacketFlowScenario({
  id: "bgp-session-establishment-and-decision-process",
  title: "BGP: establishing sessions and deciding between two paths",
  description: "Watch R1 and R3 move through the BGP finite state machine to Established, then watch R3 receive the same prefix from two different peers and apply the decision process to pick a best path.",
  defaultSpeed: 1,
  devices: [
    { id: "r1", label: "R1 (AS 65001)", role: "eBGP peer, originates the prefix", x: 160, y: 60 },
    { id: "r2", label: "R2 (AS 65003)", role: "eBGP peer, forwards from AS 65004", x: 160, y: 280 },
    { id: "r3", label: "R3 (AS 65002)", role: "runs the decision process", x: 560, y: 170 },
  ],
  links: [
    { id: "r1-r3", from: "r1", to: "r3" },
    { id: "r2-r3", from: "r2", to: "r3" },
  ],
  steps: [
    {
      id: "idle-state",
      title: "R1 and R3 start in the Idle state",
      explanation: "Neither router has attempted a connection yet. Idle is the BGP finite state machine's starting point for every peering relationship — R1's session with R3 starts here, the same way R2's will.",
      durationMs: 2200,
      activeDeviceIds: ["r1", "r3"],
      activeLinkIds: [],
      summaryFields: [
        { label: "R1 state", value: "Idle" },
        { label: "R3 state", value: "Idle" },
      ],
      detailFields: [],
    },
    {
      id: "connect-state",
      title: "R1 attempts a TCP connection: Connect",
      explanation: "R1 moves to Connect and tries to open a TCP connection to R3 on port 179. If this attempt failed, BGP would fall back to Active and keep retrying; here the attempt succeeds.",
      durationMs: 1800,
      activeDeviceIds: ["r1"],
      activeLinkIds: [],
      summaryFields: [
        { label: "R1 state", value: "Connect", changed: true },
      ],
      detailFields: [
        { label: "On failure", value: "Falls back to Active and retries the TCP connection" },
      ],
    },
    {
      id: "tcp-connection-established",
      title: "A TCP connection forms on port 179",
      explanation: "R1 completes a TCP three-way handshake (SYN, SYN-ACK, ACK) with R3 on TCP port 179. Once the connection is up, both routers move from Connect to OpenSent.",
      durationMs: 1800,
      activeDeviceIds: ["r1", "r3"],
      activeLinkIds: ["r1-r3"],
      packet: { kind: "packet", label: "TCP handshake (port 179)", from: "r1", to: "r3" },
      summaryFields: [
        { label: "Transport", value: "TCP port 179" },
        { label: "R1 state", value: "OpenSent", changed: true },
        { label: "R3 state", value: "OpenSent", changed: true },
      ],
      detailFields: [],
    },
    {
      id: "r1-sends-open",
      title: "R1 sends an OPEN message",
      explanation: "R1 sends a BGP OPEN message announcing its own AS number, BGP version, hold time, and BGP Identifier (Router ID).",
      durationMs: 1800,
      activeDeviceIds: ["r1", "r3"],
      activeLinkIds: ["r1-r3"],
      packet: { kind: "packet", label: "BGP OPEN", from: "r1", to: "r3" },
      summaryFields: [
        { label: "Message type", value: "OPEN" },
        { label: "My AS", value: "65001" },
        { label: "BGP Identifier", value: "1.1.1.1" },
      ],
      detailFields: [
        { label: "BGP version", value: "4" },
        { label: "Hold time", value: "180 seconds" },
      ],
    },
    {
      id: "r3-sends-open",
      title: "R3 replies with its own OPEN message",
      explanation: "R3 sends its OPEN message back. Both routers now have each other's AS number and Router ID and move to OpenConfirm.",
      durationMs: 1800,
      activeDeviceIds: ["r3", "r1"],
      activeLinkIds: ["r1-r3"],
      packet: { kind: "packet", label: "BGP OPEN", from: "r3", to: "r1" },
      summaryFields: [
        { label: "Message type", value: "OPEN" },
        { label: "My AS", value: "65002" },
        { label: "BGP Identifier", value: "2.2.2.2" },
      ],
      detailFields: [
        { label: "R1 state", value: "OpenConfirm", changed: true },
        { label: "R3 state", value: "OpenConfirm", changed: true },
      ],
    },
    {
      id: "keepalives-exchanged-established",
      title: "KEEPALIVEs confirm the session: Established",
      explanation: "Both routers exchange KEEPALIVE messages to confirm the OPEN parameters were accepted. The session reaches Established — the only state in which routes can be exchanged.",
      durationMs: 2200,
      activeDeviceIds: ["r1", "r3"],
      activeLinkIds: ["r1-r3"],
      packet: { kind: "packet", label: "BGP KEEPALIVE", from: "r1", to: "r3" },
      summaryFields: [
        { label: "Message type", value: "KEEPALIVE" },
        { label: "R1 state", value: "Established", changed: true },
        { label: "R3 state", value: "Established", changed: true },
      ],
      detailFields: [],
    },
    {
      id: "r2-also-establishes-with-r3",
      title: "R2 goes through the same process with R3",
      explanation: "R2 and R3 independently run through the exact same Idle-to-Established sequence just shown for R1 — it isn't replayed step by step here. Once both sessions are up, R3 is peered with two separate autonomous systems that can both advertise the same prefix.",
      durationMs: 2200,
      activeDeviceIds: ["r2", "r3"],
      activeLinkIds: ["r2-r3"],
      summaryFields: [
        { label: "R2–R3 session", value: "Established", changed: true },
        { label: "R3's sessions", value: "R1 and R2, both Established" },
      ],
      detailFields: [],
    },
    {
      id: "r1-advertises-prefix",
      title: "R1 advertises 203.0.113.0/24, originating it",
      explanation: "R1 sends an UPDATE for 203.0.113.0/24. Since R1 is this network's true source, its AS_PATH lists only its own AS — the shortest an AS_PATH can be.",
      durationMs: 2200,
      activeDeviceIds: ["r1", "r3"],
      activeLinkIds: ["r1-r3"],
      packet: { kind: "packet", label: "BGP UPDATE: 203.0.113.0/24", from: "r1", to: "r3" },
      summaryFields: [
        { label: "Message type", value: "UPDATE" },
        { label: "Prefix", value: "203.0.113.0/24" },
        { label: "AS_PATH", value: "65001 (1 AS)" },
      ],
      detailFields: [
        { label: "NEXT_HOP", value: "192.0.2.1" },
        { label: "ORIGIN", value: "IGP" },
      ],
    },
    {
      id: "r2-advertises-prefix",
      title: "R2 also advertises 203.0.113.0/24, learned from AS 65004",
      explanation: "R2 advertises the same prefix, but it isn't the source — it learned this route from AS 65004 and prepended its own AS number before passing it on, so its AS_PATH now lists two autonomous systems instead of one.",
      durationMs: 2200,
      activeDeviceIds: ["r2", "r3"],
      activeLinkIds: ["r2-r3"],
      packet: { kind: "packet", label: "BGP UPDATE: 203.0.113.0/24", from: "r2", to: "r3" },
      summaryFields: [
        { label: "Message type", value: "UPDATE" },
        { label: "Prefix", value: "203.0.113.0/24" },
        { label: "AS_PATH", value: "65003 65004 (2 ASes)" },
      ],
      detailFields: [
        { label: "NEXT_HOP", value: "198.51.100.1" },
        { label: "ORIGIN", value: "IGP" },
      ],
    },
    {
      id: "r3-runs-the-decision-process",
      title: "R3 compares both routes: LOCAL_PREF ties, AS_PATH decides",
      explanation: "R3 now holds two routes to the same prefix and has to pick one. Both arrived over eBGP with no LOCAL_PREF attribute attached — LOCAL_PREF only travels over iBGP — so R3 assigns the same local default to each, a tie. The decision process moves to the next criterion, AS_PATH length, which breaks the tie immediately: R1's path is 1 AS long, R2's is 2.",
      durationMs: 2800,
      activeDeviceIds: ["r1", "r2", "r3"],
      activeLinkIds: [],
      summaryFields: [
        { label: "LOCAL_PREF (both routes)", value: "100 — tie, local default" },
        { label: "AS_PATH comparison", value: "R1 (1 AS) beats R2 (2 ASes)", changed: true },
      ],
      detailFields: [
        { label: "Full decision order", value: "LOCAL_PREF → AS_PATH length → ORIGIN → MED → eBGP over iBGP → IGP metric to NEXT_HOP → Router ID" },
      ],
    },
    {
      id: "r3-installs-best-path",
      title: "R3 installs the route via R1",
      explanation: "With AS_PATH length already breaking the tie, R3 never needs to check ORIGIN, MED, or any later criterion for this prefix — the decision process stops at the very first comparison that isn't a tie.",
      durationMs: 2600,
      activeDeviceIds: ["r1", "r3"],
      activeLinkIds: ["r1-r3"],
      summaryFields: [
        { label: "Installed route", value: "203.0.113.0/24 via R1", changed: true },
        { label: "Decided by", value: "AS_PATH length" },
      ],
      detailFields: [],
      stateNote: "If AS_PATH had also tied, R3 would have moved on to ORIGIN, then MED (only between routes from the same neighboring AS), then preferred eBGP over iBGP, then the IGP metric to NEXT_HOP, and finally the lowest Router ID as a last resort.",
    },
  ],
} as const);
