import { parseLayerModelsLab } from "./layer-models.schema";

export const layerModelsLab = parseLayerModelsLab({
  osiLayers: [
    { number: 7, name: "Application", summary: "Provides network services to user applications.", examples: ["HTTP", "DNS", "DHCP"] },
    { number: 6, name: "Presentation", summary: "Represents, encrypts, and compresses application data.", examples: ["TLS", "UTF-8"] },
    { number: 5, name: "Session", summary: "Coordinates conversations between applications.", examples: ["Session checkpoints", "Dialog control"] },
    { number: 4, name: "Transport", summary: "Delivers data between application processes using ports.", examples: ["TCP", "UDP", "Ports"] },
    { number: 3, name: "Network", summary: "Addresses packets and moves them between networks.", examples: ["IPv4", "Routing"] },
    { number: 2, name: "Data Link", summary: "Delivers frames across one local network link.", examples: ["Ethernet", "Wi-Fi", "MAC addresses"] },
    { number: 1, name: "Physical", summary: "Carries bits as electrical, optical, or radio signals.", examples: ["Copper", "Fiber", "Radio"] },
  ],
  tcpIpLayers: [
    { id: "application", name: "Application", summary: "Combines application, representation, and conversation services.", examples: ["HTTP", "DNS", "DHCP", "TLS"] },
    { id: "transport", name: "Transport", summary: "Provides process-to-process delivery and port addressing.", examples: ["TCP", "UDP", "Ports"] },
    { id: "internet", name: "Internet", summary: "Provides logical addressing and delivery across networks.", examples: ["IPv4", "Routing"] },
    { id: "network-access", name: "Network Access", summary: "Handles local-link delivery and physical transmission.", examples: ["Ethernet", "Wi-Fi", "MAC addresses", "Bits"] },
  ],
  mapping: [
    {
      tcpIpLayer: "application",
      osiLayers: [7, 6, 5],
      explanation: "The TCP/IP Application layer covers the work described by OSI Application, Presentation, and Session layers.",
    },
    {
      tcpIpLayer: "transport",
      osiLayers: [4],
      explanation: "Both models use a Transport layer for ports and process-to-process delivery.",
    },
    {
      tcpIpLayer: "internet",
      osiLayers: [3],
      explanation: "The TCP/IP Internet layer corresponds to the OSI Network layer and its IP addressing and routing work.",
    },
    {
      tcpIpLayer: "network-access",
      osiLayers: [2, 1],
      explanation: "The TCP/IP Network Access layer combines OSI local-frame delivery and physical signaling.",
    },
  ],
  encapsulationSteps: [
    {
      id: "sender-application-data",
      direction: "encapsulation",
      title: "The browser creates data",
      plainExplanation: "The browser prepares the request it wants the server to receive.",
      technicalExplanation: "At the sender, HTTP produces application data before lower layers add their delivery information.",
      activeOsiLayer: 7,
      activeTcpIpLayer: "application",
      pdu: "Data",
      addedInformation: "HTTP request data",
      durationMs: 2400,
    },
    {
      id: "sender-transport-segment",
      direction: "encapsulation",
      title: "Transport adds ports",
      plainExplanation: "Transport labels which applications are talking at each endpoint.",
      technicalExplanation: "TCP adds source and destination ports to form a segment. UDP would form a datagram instead.",
      activeOsiLayer: 4,
      activeTcpIpLayer: "transport",
      pdu: "Segment",
      addedInformation: "TCP header with source and destination ports",
      durationMs: 2600,
    },
    {
      id: "sender-internet-packet",
      direction: "encapsulation",
      title: "Internet adds IP addresses",
      plainExplanation: "IP identifies the source and destination hosts across networks.",
      technicalExplanation: "IPv4 wraps the transport segment with an IP header to form a packet that routers can forward.",
      activeOsiLayer: 3,
      activeTcpIpLayer: "internet",
      pdu: "Packet",
      addedInformation: "IPv4 header with source and destination IP addresses",
      durationMs: 2600,
    },
    {
      id: "sender-link-frame",
      direction: "encapsulation",
      title: "Network access builds a frame",
      plainExplanation: "The sender prepares the packet for the next device on its local link.",
      technicalExplanation: "Ethernet adds a header and trailer around the IP packet, using local source and destination MAC addresses.",
      activeOsiLayer: 2,
      activeTcpIpLayer: "network-access",
      pdu: "Frame",
      addedInformation: "Ethernet header and trailer",
      durationMs: 2600,
    },
    {
      id: "physical-transmission",
      direction: "transmission",
      title: "The frame becomes signals",
      plainExplanation: "The link carries the frame as a stream of bits.",
      technicalExplanation: "The physical medium represents bits with electrical, optical, or radio signals for one link at a time.",
      activeOsiLayer: 1,
      activeTcpIpLayer: "network-access",
      pdu: "Bits",
      addedInformation: "Physical encoding for the local medium",
      durationMs: 2200,
    },
    {
      id: "receiver-link-frame",
      direction: "decapsulation",
      title: "The receiver reconstructs the frame",
      plainExplanation: "The destination network interface turns the received signals back into a frame.",
      technicalExplanation: "The receiver validates and removes the local Ethernet information before passing the contained IP packet upward.",
      activeOsiLayer: 2,
      activeTcpIpLayer: "network-access",
      pdu: "Frame",
      addedInformation: "Ethernet header and trailer examined and removed",
      durationMs: 2600,
    },
    {
      id: "receiver-internet-packet",
      direction: "decapsulation",
      title: "IP delivers the packet upward",
      plainExplanation: "The receiver confirms that the packet is addressed to this host.",
      technicalExplanation: "The IPv4 header is examined and removed, exposing the transport segment.",
      activeOsiLayer: 3,
      activeTcpIpLayer: "internet",
      pdu: "Packet",
      addedInformation: "IPv4 header examined and removed",
      durationMs: 2400,
    },
    {
      id: "receiver-transport-segment",
      direction: "decapsulation",
      title: "Transport finds the application",
      plainExplanation: "The destination port directs the content to the correct server process.",
      technicalExplanation: "TCP processes its segment header and hands the application data to the process identified by the destination port.",
      activeOsiLayer: 4,
      activeTcpIpLayer: "transport",
      pdu: "Segment",
      addedInformation: "TCP header examined and removed",
      durationMs: 2600,
    },
    {
      id: "receiver-application-data",
      direction: "decapsulation",
      title: "The server receives data",
      plainExplanation: "The original browser request reaches the destination application.",
      technicalExplanation: "The server application interprets the recovered HTTP request data and can prepare a response.",
      activeOsiLayer: 7,
      activeTcpIpLayer: "application",
      pdu: "Data",
      addedInformation: "HTTP request delivered to the server application",
      durationMs: 2400,
    },
  ],
});
