import { publicConnectionMedia } from "./connection-media.data";
import {
  parseConnectionMediaCatalog,
  type ConnectionMediaCatalog,
  type ConnectionScenario,
} from "./connection-media.schema";

const scenarios: readonly ConnectionScenario[] = [
  {
    id: "home-desktop",
    title: "Desktop near a home router",
    source: "A fixed desktop computer",
    destination: "A home router",
    distance: "8 metres in the same room",
    minimumBandwidth: "1 Gbit/s for local backups and downloads",
    latencySensitivity: "medium",
    environment: "A quiet home office with a clear cable route",
    mobilityRequired: false,
    reliabilityPriority: "standard",
    budget: "low",
    recommendedMediumId: "copper",
    evaluations: {
      copper: { outcome: "recommended", decisiveRequirements: ["The short 8-metre distance", "The fixed desktop", "The low budget"], explanation: "Copper Ethernet is the straightforward fit for a fixed desktop close to the router and can meet the required 1 Gbit/s link." },
      fibre: { outcome: "workable-with-trade-offs", decisiveRequirements: ["The short 8-metre distance", "The low budget"], explanation: "Fibre can carry the traffic, but compatible optics and installation add cost without solving a need that nearby copper already meets." },
      wireless: { outcome: "workable-with-trade-offs", decisiveRequirements: ["The 1 Gbit/s minimum bandwidth", "The fixed desktop"], explanation: "Wireless may work in the same room, but its shared airtime makes a fixed desktop connection less predictable than a direct cable." },
    },
  },
  {
    id: "mobile-office",
    title: "Laptop used throughout a small office",
    source: "A staff laptop",
    destination: "Office network services",
    distance: "Up to 20 metres while moving between rooms",
    minimumBandwidth: "100 Mbit/s for cloud work and calls",
    latencySensitivity: "medium",
    environment: "A small office with managed access-point coverage",
    mobilityRequired: true,
    reliabilityPriority: "high",
    budget: "medium",
    recommendedMediumId: "wireless",
    evaluations: {
      copper: { outcome: "workable-with-trade-offs", decisiveRequirements: ["Movement between rooms", "High reliability"], explanation: "Copper gives a reliable connection at a desk, but a cable prevents the laptop from moving freely through the office." },
      fibre: { outcome: "unsuitable", decisiveRequirements: ["Movement between rooms", "The staff laptop"], explanation: "A fibre run is a fixed, specialist link and does not meet the laptop's mobility requirement." },
      wireless: { outcome: "recommended", decisiveRequirements: ["Movement between rooms", "100 Mbit/s minimum bandwidth"], explanation: "Managed wireless coverage lets the laptop move between rooms while still meeting ordinary office traffic needs." },
    },
  },
  {
    id: "noisy-workshop",
    title: "Fixed workstation in a noisy workshop",
    source: "A fixed control workstation",
    destination: "A local engineering server",
    distance: "35 metres",
    minimumBandwidth: "1 Gbit/s for design files",
    latencySensitivity: "high",
    environment: "Machinery creates electrical noise and radio obstruction",
    mobilityRequired: false,
    reliabilityPriority: "high",
    budget: "medium",
    recommendedMediumId: "fibre",
    evaluations: {
      copper: { outcome: "workable-with-trade-offs", decisiveRequirements: ["Electrical noise", "High reliability"], explanation: "Copper can reach 35 metres, but the machinery's electrical noise requires careful installation and makes the high-reliability link less robust." },
      fibre: { outcome: "recommended", decisiveRequirements: ["Electrical noise", "1 Gbit/s minimum bandwidth", "High reliability"], explanation: "Fibre avoids electromagnetic interference from the machinery and provides a stable fixed link for the workstation." },
      wireless: { outcome: "unsuitable", decisiveRequirements: ["Radio obstruction", "High reliability", "High latency sensitivity"], explanation: "Obstruction and industrial radio noise make shared wireless too uncertain for this latency-sensitive, reliable workstation link." },
    },
  },
  {
    id: "campus-buildings",
    title: "Two buildings on a campus",
    source: "The network room in one building",
    destination: "The network room in another building",
    distance: "450 metres outdoors",
    minimumBandwidth: "10 Gbit/s for shared services",
    latencySensitivity: "high",
    environment: "An outdoor route with buried conduit available",
    mobilityRequired: false,
    reliabilityPriority: "high",
    budget: "high",
    recommendedMediumId: "fibre",
    evaluations: {
      copper: { outcome: "unsuitable", decisiveRequirements: ["The 450-metre distance", "10 Gbit/s minimum bandwidth"], explanation: "The 450-metre building-to-building run exceeds the practical distance for common twisted-pair Ethernet." },
      fibre: { outcome: "recommended", decisiveRequirements: ["The 450-metre distance", "10 Gbit/s minimum bandwidth", "High reliability"], explanation: "Fibre in the available conduit supports the campus distance, capacity, and reliability requirements." },
      wireless: { outcome: "workable-with-trade-offs", decisiveRequirements: ["10 Gbit/s minimum bandwidth", "High reliability"], explanation: "A point-to-point wireless bridge could cross the gap, but alignment, weather, and shared radio conditions make it a weaker fit for the required capacity and reliability." },
    },
  },
  {
    id: "data-centre-interconnect",
    title: "High-capacity data-centre interconnect",
    source: "One data-centre switch",
    destination: "A second data-centre switch",
    distance: "300 metres across a data-centre campus",
    minimumBandwidth: "40 Gbit/s for replicated services",
    latencySensitivity: "high",
    environment: "A controlled campus route between secure equipment rooms",
    mobilityRequired: false,
    reliabilityPriority: "high",
    budget: "high",
    recommendedMediumId: "fibre",
    evaluations: {
      copper: { outcome: "unsuitable", decisiveRequirements: ["The 300-metre distance", "40 Gbit/s minimum bandwidth"], explanation: "Copper is not a reasonable fit for the 300-metre, 40 Gbit/s interconnect requirement." },
      fibre: { outcome: "recommended", decisiveRequirements: ["The 300-metre distance", "40 Gbit/s minimum bandwidth", "High reliability"], explanation: "Compatible fibre optics provide the capacity, campus reach, and reliable fixed connection needed between the two switches." },
      wireless: { outcome: "unsuitable", decisiveRequirements: ["40 Gbit/s minimum bandwidth", "High reliability", "High latency sensitivity"], explanation: "Shared wireless airtime is not appropriate for this high-capacity, latency-sensitive data-centre interconnect." },
    },
  },
  {
    id: "temporary-classroom",
    title: "Temporary classroom network",
    source: "Student laptops",
    destination: "The school network",
    distance: "15 metres inside a temporary room",
    minimumBandwidth: "100 Mbit/s for class materials",
    latencySensitivity: "low",
    environment: "A short-term classroom with an existing nearby access point",
    mobilityRequired: true,
    reliabilityPriority: "standard",
    budget: "low",
    recommendedMediumId: "wireless",
    evaluations: {
      copper: { outcome: "workable-with-trade-offs", decisiveRequirements: ["Temporary room", "Student mobility"], explanation: "Copper can serve a fixed teacher station, but running cables to moving student laptops is inconvenient for the temporary classroom." },
      fibre: { outcome: "unsuitable", decisiveRequirements: ["Temporary room", "Low budget", "Student mobility"], explanation: "Installing fibre for a short-term, low-budget classroom does not meet the practical mobility or setup constraints." },
      wireless: { outcome: "recommended", decisiveRequirements: ["Student mobility", "Temporary room", "100 Mbit/s minimum bandwidth"], explanation: "The nearby access point gives mobile student devices a practical short-term connection for ordinary classroom traffic." },
    },
  },
];

export const connectionMediaCatalog: ConnectionMediaCatalog = parseConnectionMediaCatalog({
  media: publicConnectionMedia,
  scenarios,
});

export const accountConnectionScenarios = connectionMediaCatalog.scenarios;
