import { parsePacketFlowScenario, type PacketFlowScenario } from "./packet-flow.schema";

export const networkCommunicationScenario: PacketFlowScenario = parsePacketFlowScenario({
  id: "network-communication-arp-icmp",
  title: "ARP and ICMP across two networks",
  description: "Follow a ping from a PC to a remote server and back.",
  defaultSpeed: 1,
  devices: [
    { id: "pc", label: "PC", role: "host", x: 80, y: 240 },
    { id: "switch", label: "Switch", role: "layer 2 switch", x: 280, y: 240 },
    { id: "router", label: "Router", role: "default gateway", x: 520, y: 240 },
    { id: "server", label: "Server", role: "remote host", x: 720, y: 240 },
  ],
  links: [
    { id: "pc-switch", from: "pc", to: "switch" },
    { id: "switch-router", from: "switch", to: "router" },
    { id: "router-server", from: "router", to: "server" },
  ],
  steps: [
    {
      id: "pc-determines-server-is-remote",
      title: "The PC recognizes a remote destination",
      explanation: "The PC compares 198.51.100.20 with its own network and sees that the server is remote, so it must send the first frame to its default gateway.",
      durationMs: 2600,
      activeDeviceIds: ["pc"],
      activeLinkIds: [],
      summaryFields: [{ label: "PC IP", value: "192.0.2.10" }, { label: "Server IP", value: "198.51.100.20" }],
      detailFields: [{ label: "Next hop", value: "Default gateway 192.0.2.1" }],
      stateNote: "The PC needs the gateway's MAC address before it can send an Ethernet frame.",
    },
    {
      id: "pc-broadcasts-arp-request",
      title: "The PC broadcasts an ARP request",
      explanation: "The PC asks, “Who has 192.0.2.1?” in a broadcast Ethernet frame so every device on this LAN can hear it.",
      durationMs: 1800,
      activeDeviceIds: ["pc", "switch"],
      activeLinkIds: ["pc-switch"],
      packet: { kind: "frame", label: "ARP request", from: "pc", to: "switch", broadcast: true },
      summaryFields: [{ label: "Ethernet destination", value: "FF:FF:FF:FF:FF:FF" }, { label: "Target IP", value: "192.0.2.1" }],
      detailFields: [{ label: "Sender MAC", value: "00:11:22:33:44:10" }, { label: "Sender IP", value: "192.0.2.10" }],
    },
    {
      id: "switch-floods-arp-request",
      title: "The switch floods the broadcast",
      explanation: "A switch forwards a broadcast out its other LAN port; it does not route the packet. The ARP request reaches the router.",
      durationMs: 1800,
      activeDeviceIds: ["switch", "router"],
      activeLinkIds: ["switch-router"],
      packet: { kind: "frame", label: "ARP request", from: "switch", to: "router", broadcast: true },
      summaryFields: [{ label: "Ethernet destination", value: "FF:FF:FF:FF:FF:FF" }, { label: "Target IP", value: "192.0.2.1" }],
      detailFields: [{ label: "Flooded by", value: "Switch" }],
    },
    {
      id: "router-replies-to-arp",
      title: "The router replies with its LAN MAC address",
      explanation: "The router owns 192.0.2.1, so it sends an ARP reply with the MAC address of its LAN interface.",
      durationMs: 1800,
      activeDeviceIds: ["router", "switch"],
      activeLinkIds: ["switch-router"],
      packet: { kind: "frame", label: "ARP reply", from: "router", to: "switch" },
      summaryFields: [{ label: "Router LAN IP", value: "192.0.2.1" }, { label: "Router LAN MAC", value: "00:11:22:33:44:01" }],
      detailFields: [{ label: "Destination MAC", value: "00:11:22:33:44:10" }],
    },
    {
      id: "switch-forwards-arp-reply",
      title: "The switch forwards the ARP reply to the PC",
      explanation: "The switch forwards the unicast ARP reply back to the PC's port.",
      durationMs: 1800,
      activeDeviceIds: ["switch", "pc"],
      activeLinkIds: ["pc-switch"],
      packet: { kind: "frame", label: "ARP reply", from: "switch", to: "pc" },
      summaryFields: [{ label: "Router LAN MAC", value: "00:11:22:33:44:01" }],
      detailFields: [{ label: "Destination MAC", value: "00:11:22:33:44:10" }],
    },
    {
      id: "pc-records-arp-mapping",
      title: "The PC records the ARP mapping",
      explanation: "The PC stores the gateway mapping so it can address the first Ethernet frame to the router.",
      durationMs: 2600,
      activeDeviceIds: ["pc"],
      activeLinkIds: [],
      summaryFields: [{ label: "ARP entry", value: "192.0.2.1 → 00:11:22:33:44:01" }],
      detailFields: [{ label: "Gateway", value: "192.0.2.1" }],
      stateNote: "The ARP table now has the next-hop MAC address.",
    },
    {
      id: "pc-creates-icmp-echo-request",
      title: "The PC creates an ICMP echo request",
      explanation: "The IP packet keeps the server as its destination, while the new Ethernet frame uses the gateway as its local destination.",
      durationMs: 2600,
      activeDeviceIds: ["pc"],
      activeLinkIds: [],
      summaryFields: [{ label: "ICMP", value: "Echo request" }, { label: "Destination IP", value: "198.51.100.20" }],
      detailFields: [{ label: "Source IP", value: "192.0.2.10" }, { label: "Destination MAC", value: "00:11:22:33:44:01" }],
    },
    {
      id: "pc-sends-icmp-request",
      title: "The PC sends the echo request to the switch",
      explanation: "The PC sends its unicast frame toward the gateway, first crossing the link to the switch.",
      durationMs: 1800,
      activeDeviceIds: ["pc", "switch"],
      activeLinkIds: ["pc-switch"],
      packet: { kind: "frame", label: "ICMP echo request", from: "pc", to: "switch" },
      summaryFields: [{ label: "Source IP", value: "192.0.2.10" }, { label: "Destination IP", value: "198.51.100.20" }],
      detailFields: [{ label: "Source MAC", value: "00:11:22:33:44:10" }, { label: "Destination MAC", value: "00:11:22:33:44:01" }],
    },
    {
      id: "switch-forwards-icmp-request",
      title: "The switch forwards the unicast frame",
      explanation: "The switch recognizes the gateway's MAC address and forwards the unicast frame to the router; it does not change the IP packet.",
      durationMs: 1800,
      activeDeviceIds: ["switch", "router"],
      activeLinkIds: ["switch-router"],
      packet: { kind: "frame", label: "ICMP echo request", from: "switch", to: "router" },
      summaryFields: [{ label: "Destination MAC", value: "00:11:22:33:44:01" }],
      detailFields: [{ label: "Destination IP", value: "198.51.100.20" }],
    },
    {
      id: "router-routes-icmp-request",
      title: "The router routes the echo request",
      explanation: "The router removes the incoming Ethernet frame, examines the route to the server, reduces the IP TTL, and prepares a new Ethernet frame for the server-side network.",
      durationMs: 2600,
      activeDeviceIds: ["router"],
      activeLinkIds: [],
      summaryFields: [{ label: "Source IP", value: "192.0.2.10" }, { label: "Destination IP", value: "198.51.100.20" }],
      detailFields: [{ label: "TTL", value: "63", changed: true }, { label: "Outgoing source MAC", value: "00:11:22:33:55:01", changed: true }, { label: "Outgoing destination MAC", value: "00:11:22:33:55:20", changed: true }],
      stateNote: "Routing replaces the Ethernet frame but preserves the end-to-end IP addresses.",
    },
    {
      id: "router-sends-icmp-request",
      title: "The router sends a new frame to the server",
      explanation: "On the server-side network, the router sends the unchanged IP packet in a new frame addressed to the server.",
      durationMs: 1800,
      activeDeviceIds: ["router", "server"],
      activeLinkIds: ["router-server"],
      packet: { kind: "frame", label: "ICMP echo request", from: "router", to: "server" },
      summaryFields: [{ label: "Source IP", value: "192.0.2.10" }, { label: "Destination IP", value: "198.51.100.20" }],
      detailFields: [{ label: "Source MAC", value: "00:11:22:33:55:01" }, { label: "Destination MAC", value: "00:11:22:33:55:20" }],
    },
    {
      id: "server-receives-icmp-request",
      title: "The server receives the echo request",
      explanation: "The server accepts the frame addressed to its MAC address and delivers the ICMP echo request to its IP stack.",
      durationMs: 2600,
      activeDeviceIds: ["server"],
      activeLinkIds: [],
      summaryFields: [{ label: "Server IP", value: "198.51.100.20" }, { label: "ICMP", value: "Echo request received" }],
      detailFields: [{ label: "Server MAC", value: "00:11:22:33:55:20" }],
    },
    {
      id: "server-creates-icmp-echo-reply",
      title: "The server creates an ICMP echo reply",
      explanation: "The server reverses the IP endpoints for its echo reply and addresses its local Ethernet frame to the router's server-side interface.",
      durationMs: 2600,
      activeDeviceIds: ["server"],
      activeLinkIds: [],
      summaryFields: [{ label: "ICMP", value: "Echo reply" }, { label: "Source IP", value: "198.51.100.20" }],
      detailFields: [{ label: "Destination IP", value: "192.0.2.10" }, { label: "Destination MAC", value: "00:11:22:33:55:01" }],
    },
    {
      id: "server-sends-icmp-reply",
      title: "The server sends the echo reply to the router",
      explanation: "The first return frame crosses from the server to its local gateway, while the IP packet remains addressed from the server to the PC.",
      durationMs: 1800,
      activeDeviceIds: ["server", "router"],
      activeLinkIds: ["router-server"],
      packet: { kind: "frame", label: "ICMP echo reply", from: "server", to: "router" },
      summaryFields: [{ label: "Source IP", value: "198.51.100.20" }, { label: "Destination IP", value: "192.0.2.10" }],
      detailFields: [{ label: "Source MAC", value: "00:11:22:33:55:20" }, { label: "Destination MAC", value: "00:11:22:33:55:01" }],
    },
    {
      id: "router-routes-icmp-reply",
      title: "The router routes the echo reply back",
      explanation: "The router removes the return frame, sees that 192.0.2.10 is on its LAN, and creates a new frame for the PC-side network without changing the IP endpoints.",
      durationMs: 2600,
      activeDeviceIds: ["router"],
      activeLinkIds: [],
      summaryFields: [{ label: "Source IP", value: "198.51.100.20" }, { label: "Destination IP", value: "192.0.2.10" }],
      detailFields: [{ label: "TTL", value: "63", changed: true }, { label: "Outgoing destination MAC", value: "00:11:22:33:44:10", changed: true }],
      stateNote: "The reply's IP source and destination remain server to PC across the router.",
    },
    {
      id: "router-sends-icmp-reply",
      title: "The router sends the reply toward the switch",
      explanation: "The router's new PC-side frame uses its LAN MAC as source and the PC MAC as destination.",
      durationMs: 1800,
      activeDeviceIds: ["router", "switch"],
      activeLinkIds: ["switch-router"],
      packet: { kind: "frame", label: "ICMP echo reply", from: "router", to: "switch" },
      summaryFields: [{ label: "Source IP", value: "198.51.100.20" }, { label: "Destination IP", value: "192.0.2.10" }],
      detailFields: [{ label: "Source MAC", value: "00:11:22:33:44:01" }, { label: "Destination MAC", value: "00:11:22:33:44:10" }],
    },
    {
      id: "switch-forwards-icmp-reply",
      title: "The switch forwards the reply to the PC",
      explanation: "The switch forwards the unicast reply on the link to the PC; it still does not route the IP packet.",
      durationMs: 1800,
      activeDeviceIds: ["switch", "pc"],
      activeLinkIds: ["pc-switch"],
      packet: { kind: "frame", label: "ICMP echo reply", from: "switch", to: "pc" },
      summaryFields: [{ label: "Source IP", value: "198.51.100.20" }, { label: "Destination IP", value: "192.0.2.10" }],
      detailFields: [{ label: "Destination MAC", value: "00:11:22:33:44:10" }],
    },
    {
      id: "pc-receives-icmp-echo-reply",
      title: "The PC receives the echo reply",
      explanation: "The PC receives the reply from the remote server, completing the round trip.",
      durationMs: 2600,
      activeDeviceIds: ["pc"],
      activeLinkIds: [],
      summaryFields: [{ label: "ICMP", value: "Echo reply received" }, { label: "Round trip", value: "PC → Server → PC" }],
      detailFields: [{ label: "Source IP", value: "198.51.100.20" }, { label: "Destination IP", value: "192.0.2.10" }],
      stateNote: "Ping succeeds.",
    },
  ],
} as const);
