import { parsePacketFlowScenario, type PacketFlowScenario } from "@/features/packet-flow/packet-flow.schema";

export const ipsecTunnelEstablishmentScenario: PacketFlowScenario = parsePacketFlowScenario({
  id: "ipsec-site-to-site-tunnel-establishment",
  title: "IPsec: building a site-to-site tunnel and carrying traffic through it",
  description: "Watch two site-to-site VPN routers negotiate an IKEv2 tunnel in two round trips, then watch a real packet leave one LAN, cross the public Internet wrapped in ESP tunnel mode, and arrive unmodified on the other LAN.",
  defaultSpeed: 1,
  devices: [
    { id: "host-a", label: "Host 10.0.1.5", role: "10.0.1.0/24 LAN", x: 60, y: 160 },
    { id: "gateway-a", label: "R1", role: "public IP 70.0.0.1", x: 230, y: 160 },
    { id: "internet", label: "Internet", role: "public IPsec tunnel path", x: 400, y: 70 },
    { id: "gateway-b", label: "R2", role: "public IP 80.0.0.1", x: 570, y: 160 },
    { id: "host-b", label: "Host 10.0.2.5", role: "10.0.2.0/24 LAN", x: 740, y: 160 },
  ],
  links: [
    { id: "host-a-gateway-a", from: "host-a", to: "gateway-a" },
    { id: "gateway-a-internet", from: "gateway-a", to: "internet" },
    { id: "internet-gateway-b", from: "internet", to: "gateway-b" },
    { id: "gateway-b-host-b", from: "gateway-b", to: "host-b" },
    {
      id: "gateway-a-gateway-b", from: "gateway-a", to: "gateway-b",
      fromInterface: "FE0/1 — public IP 70.0.0.1", toInterface: "FE0/1 — public IP 80.0.0.1",
    },
  ],
  steps: [
    {
      id: "ike-sa-init-exchange",
      title: "R1 and R2 exchange IKE_SA_INIT",
      explanation: "R1 and R2 exchange IKE_SA_INIT messages across the public Internet, in the clear — Diffie-Hellman public values and nonces, along with the algorithms each is willing to use for the IKE SA itself.",
      durationMs: 2200,
      activeDeviceIds: ["gateway-a", "internet", "gateway-b"],
      activeLinkIds: ["gateway-a-gateway-b"],
      packet: { kind: "packet", label: "IKE_SA_INIT: DH public values, nonces (cleartext)", from: "gateway-a", to: "gateway-b" },
      summaryFields: [
        { label: "Exchange", value: "IKE_SA_INIT" },
        { label: "Protected", value: "No — this exchange is cleartext" },
      ],
      detailFields: [
        { label: "UDP port", value: "500" },
      ],
    },
    {
      id: "ike-channel-established",
      title: "Both sides derive keys; the IKE SA becomes encrypted",
      explanation: "Both routers independently derive the same keys from the Diffie-Hellman exchange. From this point on, the IKE SA is an encrypted and authenticated control channel — even though neither router has proven its identity yet.",
      durationMs: 2200,
      activeDeviceIds: ["gateway-a", "gateway-b"],
      activeLinkIds: [],
      summaryFields: [
        { label: "IKE SA", value: "Encrypted control channel established", changed: true },
      ],
      detailFields: [
        { label: "Identity proven yet?", value: "No — that's the next exchange" },
      ],
    },
    {
      id: "ike-auth-exchange",
      title: "R1 and R2 authenticate inside the encrypted channel",
      explanation: "Inside the now-encrypted IKE SA, each router sends its identity and proves it (for example, a pre-shared key or certificate), and both propose a Child SA to protect traffic between their two private subnets.",
      durationMs: 2200,
      activeDeviceIds: ["gateway-a", "internet", "gateway-b"],
      activeLinkIds: ["gateway-a-gateway-b"],
      packet: { kind: "packet", label: "IKE_AUTH: identity + auth (encrypted)", from: "gateway-a", to: "gateway-b" },
      summaryFields: [
        { label: "Exchange", value: "IKE_AUTH" },
        { label: "Proposed Child SA", value: "10.0.1.0/24 ↔ 10.0.2.0/24" },
      ],
      detailFields: [],
    },
    {
      id: "child-sa-negotiated",
      title: "The Child SA is negotiated",
      explanation: "Both sides agree on the Child SA's encryption and integrity algorithms and the exact traffic selectors it protects. IKEv2 has gone from nothing to a fully negotiated tunnel in just these two round trips.",
      durationMs: 2200,
      activeDeviceIds: ["gateway-a", "gateway-b"],
      activeLinkIds: [],
      summaryFields: [
        { label: "Child SA", value: "Negotiated", changed: true },
        { label: "Round trips used", value: "2 (IKE_SA_INIT + IKE_AUTH)" },
      ],
      detailFields: [],
      stateNote: "IKEv1 needed considerably more round trips to reach this same point.",
    },
    {
      id: "original-packet-needs-protection",
      title: "A host on site A sends traffic toward site B",
      explanation: "The host at 10.0.1.5 sends a plaintext packet addressed to 10.0.2.5 onto its own LAN. R1's security policy matches this traffic against the Child SA that was just negotiated.",
      durationMs: 2000,
      activeDeviceIds: ["host-a", "gateway-a"],
      activeLinkIds: ["host-a-gateway-a"],
      packet: { kind: "packet", label: "10.0.1.5 → 10.0.2.5 (plaintext, LAN)", from: "host-a", to: "gateway-a" },
      summaryFields: [
        { label: "Original packet", value: "10.0.1.5 → 10.0.2.5" },
        { label: "Matched policy", value: "Protect via negotiated Child SA" },
      ],
      detailFields: [],
    },
    {
      id: "esp-tunnel-encapsulation",
      title: "R1 wraps the whole packet in ESP tunnel mode and sends it across the Internet",
      explanation: "R1 encrypts and authenticates the entire original packet — its original header included — inside a new ESP packet, under a brand-new outer IP header from R1's public interface to R2's public interface, and sends it across the public Internet.",
      durationMs: 2200,
      activeDeviceIds: ["gateway-a", "internet", "gateway-b"],
      activeLinkIds: ["gateway-a-gateway-b"],
      packet: { kind: "packet", label: "ESP (tunnel mode): outer 70.0.0.1 → 80.0.0.1, inner 10.0.1.5 → 10.0.2.5", from: "gateway-a", to: "gateway-b" },
      summaryFields: [
        { label: "Outer header", value: "R1 → R2" },
        { label: "Inner (encrypted) packet", value: "10.0.1.5 → 10.0.2.5" },
      ],
      detailFields: [
        { label: "IP protocol", value: "50 (ESP)" },
      ],
    },
    {
      id: "gatewayb-decapsulates-and-forwards",
      title: "R2 decapsulates and forwards the original packet onto its LAN",
      explanation: "R2 decrypts and verifies the ESP packet using the Child SA, strips the outer header, and forwards the original, unmodified inner packet onto the 10.0.2.0/24 network — the host at 10.0.2.5 receives it exactly as it was sent.",
      durationMs: 2600,
      activeDeviceIds: ["gateway-b", "host-b"],
      activeLinkIds: ["gateway-b-host-b"],
      packet: { kind: "packet", label: "10.0.1.5 → 10.0.2.5 (delivered, LAN)", from: "gateway-b", to: "host-b" },
      summaryFields: [
        { label: "Outer header", value: "Removed" },
        { label: "Delivered", value: "10.0.1.5 → 10.0.2.5 (unmodified)", changed: true },
      ],
      detailFields: [],
      stateNote: "Neither original host ever needed to know IPsec was involved — the routers handled it entirely on their behalf.",
    },
  ],
} as const);
