import { parsePacketFlowScenario, type PacketFlowScenario } from "@/features/packet-flow/packet-flow.schema";

export const stickyClientRoamingScenario: PacketFlowScenario = parsePacketFlowScenario({
  id: "sticky-client-and-roaming-trigger",
  title: "The sticky client problem: why overlap alone doesn't guarantee a good roam",
  description: "Watch a client cling to a weakening AP well past the point a stronger one is available, then watch 802.11k and 802.11v pull the roam decision forward — the same cell overlap, with a very different outcome.",
  defaultSpeed: 1,
  devices: [
    { id: "ap1", label: "AP1", role: "client's current access point", x: 140, y: 170 },
    { id: "client", label: "Client", role: "walking from AP1 toward AP2", x: 400, y: 170 },
    { id: "ap2", label: "AP2", role: "access point with a stronger signal ahead", x: 660, y: 170 },
  ],
  links: [
    { id: "client-ap1", from: "client", to: "ap1" },
    { id: "client-ap2", from: "client", to: "ap2" },
  ],
  steps: [
    {
      id: "client-starts-strongly-connected-to-ap1",
      title: "The client starts right next to AP1",
      explanation: "The client is standing close to AP1 with an excellent signal. It's comfortably connected and has no reason to even think about another AP.",
      durationMs: 2200,
      activeDeviceIds: ["client", "ap1"],
      activeLinkIds: ["client-ap1"],
      summaryFields: [
        { label: "RSSI to AP1", value: "-45 dBm (excellent)" },
      ],
      detailFields: [],
    },
    {
      id: "client-walks-away-signal-degrades-but-stays-connected",
      title: "The client walks away; signal degrades, but it stays put",
      explanation: "As the client moves toward AP2's area, AP1's signal noticeably weakens. It's still \"good enough\" by the client's own standard, though, so the client doesn't even scan for alternatives yet.",
      durationMs: 2400,
      activeDeviceIds: ["client", "ap1"],
      activeLinkIds: ["client-ap1"],
      summaryFields: [
        { label: "RSSI to AP1", value: "-68 dBm (fair, declining)", changed: true },
        { label: "Client scanning?", value: "No — still above its own threshold" },
      ],
      detailFields: [],
    },
    {
      id: "ap2-is-now-the-better-choice-but-client-stays-put",
      title: "AP2 is now the better choice — but the client doesn't know that",
      explanation: "By this point the client is physically closer to AP2, which would offer a much stronger signal. But the client has no way to know that unless it actively scans, and its radio is tuned to avoid the cost of scanning and roaming as long as its current link still basically works. This is the sticky client problem.",
      durationMs: 2600,
      activeDeviceIds: ["client", "ap1"],
      activeLinkIds: ["client-ap1"],
      summaryFields: [
        { label: "RSSI to AP1", value: "-74 dBm (poor)" },
        { label: "RSSI to AP2 (unknown to client)", value: "-55 dBm (much stronger)", changed: true },
      ],
      detailFields: [
        { label: "Client still attached to", value: "AP1" },
      ],
    },
    {
      id: "client-finally-roams-only-after-signal-is-nearly-gone",
      title: "The client finally roams — only once the signal is nearly gone",
      explanation: "Only once AP1's signal crosses the client's own aggressive low threshold does it finally scan, find AP2, and roam. By now, call quality or throughput has likely already suffered for several seconds.",
      durationMs: 2600,
      activeDeviceIds: ["client", "ap2"],
      activeLinkIds: ["client-ap2"],
      packet: { kind: "frame", label: "Association Request (late roam)", from: "client", to: "ap2" },
      summaryFields: [
        { label: "RSSI to AP1 at roam", value: "-82 dBm (very poor)", changed: true },
        { label: "Roam trigger", value: "Client's own threshold only" },
      ],
      detailFields: [],
    },
    {
      id: "80211k-gives-the-client-a-neighbor-report",
      title: "With 802.11k, AP1 hands the client a neighbor report",
      explanation: "Now replay the same walk with assistance enabled. AP1 proactively sends the client a neighbor report listing AP2 and its channel, so the client can evaluate a move without blindly scanning every channel itself.",
      durationMs: 2400,
      activeDeviceIds: ["ap1", "client"],
      activeLinkIds: ["client-ap1"],
      packet: { kind: "frame", label: "802.11k Neighbor Report", from: "ap1", to: "client" },
      summaryFields: [
        { label: "Frame", value: "802.11k Neighbor Report" },
        { label: "Lists", value: "AP2 (channel, BSSID)" },
      ],
      detailFields: [],
    },
    {
      id: "80211v-proactively-suggests-the-move",
      title: "With 802.11v, AP1 proactively suggests the move",
      explanation: "AP1 also sends a BSS Transition Management request suggesting the client move to AP2 — before AP1's own signal gets critically weak. The network can see what the client's own conservative radio might not bother checking for itself.",
      durationMs: 2400,
      activeDeviceIds: ["ap1", "client"],
      activeLinkIds: ["client-ap1"],
      packet: { kind: "frame", label: "802.11v BSS Transition Management Request", from: "ap1", to: "client" },
      summaryFields: [
        { label: "Frame", value: "802.11v BSS Transition Management Request" },
        { label: "Suggests", value: "Move to AP2 now" },
      ],
      detailFields: [],
    },
    {
      id: "assisted-roam-happens-much-earlier",
      title: "The assisted roam happens much earlier",
      explanation: "With both assists in place, the client roams to AP2 while AP1's signal is still comfortably usable — well before the unassisted case's near-total signal loss.",
      durationMs: 2600,
      activeDeviceIds: ["client", "ap2"],
      activeLinkIds: ["client-ap2"],
      packet: { kind: "frame", label: "Association Request (assisted roam)", from: "client", to: "ap2" },
      summaryFields: [
        { label: "RSSI to AP1 at roam", value: "-65 dBm (still usable)", changed: true },
        { label: "Roam trigger", value: "Network-assisted (802.11k/v), not just the client's threshold", changed: true },
      ],
      detailFields: [],
    },
    {
      id: "site-design-and-client-assistance-both-matter",
      title: "Good overlap creates the opportunity — assistance is what uses it",
      explanation: "Good AP placement with enough cell overlap creates the opportunity to roam early. But as this walk showed twice, overlap alone doesn't guarantee an early roam — a client's own radio can sit on a dying signal well past the point a stronger AP was already available. 802.11k and 802.11v are what actually get the client to use the overlap the site design provided.",
      durationMs: 2800,
      activeDeviceIds: ["client", "ap1", "ap2"],
      activeLinkIds: [],
      summaryFields: [
        { label: "Unassisted roam point", value: "-82 dBm" },
        { label: "Assisted roam point", value: "-65 dBm", changed: true },
      ],
      detailFields: [],
      stateNote: "The gap between those two numbers is the entire difference between a seamless voice call and a noticeably dropped one.",
    },
  ],
} as const);
